version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force # install Hex locally (without prompt)
      - run: mix local.rebar --force # fetch a copy of rebar (without prompt)

      - restore_cache:
          keys:
            - mix-cache-{{ checksum "mix.lock" }}

      - run: mix do deps.get
      - save_cache:
          key: mix-cache-{{ checksum "mix.lock" }}
          paths: "deps"

      - run: mix test
      - run: MIX_ENV=prod mix compile
